/* eslint-disable */
import { FuseNavigationItem } from '@fuse/components/navigation';

export const defaultNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboard',
        title: 'NAVIGATION.DASHBOARD',
        translate: 'NAVIGATION.DASHBOARD',
        type: 'aside',
        icon: 'heroicons_outline:squares-2x2',
        link: '/dashboard',
        exactMatch: true,
        children: [
            {
                id: 'dashboard.index',
                title: 'NAVIGATION.DASHBOARD',
                translate: 'NAVIGATION.DASHBOARD',
                type: 'basic',
                icon: 'heroicons_outline:squares-2x2',
                link: '/dashboard',
                exactMatch: true,
            },
        ],
    },
    {
        id: 'task',
        title: 'NAVIGATION.TASK',
        translate: 'NAVIGATION.TASK',
        type: 'aside',
        icon: 'heroicons_outline:clipboard-document-list',
        link: '/task',
        exactMatch: true,
        children: [
            {
                id: 'task.index',
                title: 'NAVIGATION.TASK',
                translate: 'NAVIGATION.TASK',
                type: 'basic',
                icon: 'heroicons_outline:clipboard-document-list',
                link: '/task',
                exactMatch: true,
            },
        ],
    },
    {
        id: 'tickets',
        title: 'NAVIGATION.TICKETS',
        translate: 'NAVIGATION.TICKETS',
        type: 'aside',
        icon: 'heroicons_outline:ticket',
        badge: {
            title: '0',
            classes: 'bg-red-500 text-white',
        },
        children: [
            {
                id: 'tickets.dashboard',
                title: 'NAVIGATION.DASHBOARD',
                translate: 'NAVIGATION.DASHBOARD',
                type: 'basic',
                icon: 'heroicons_outline:chart-pie',
                link: '/tickets/dashboard',
            },
            {
                id: 'tickets.list',
                title: 'NAVIGATION.TICKETS',
                translate: 'NAVIGATION.TICKETS',
                type: 'basic',
                icon: 'heroicons_outline:ticket',
                link: '/tickets/data',
            },
            {
                id: 'tickets.create',
                title: 'NAVIGATION.CREATE_TICKET',
                translate: 'NAVIGATION.CREATE_TICKET',
                type: 'basic',
                icon: 'heroicons_outline:plus-circle',
                link: '/tickets/create',
            },
            {
                id: 'tickets.detail',
                title: 'Ticket Detail',
                type: 'basic',
                link: '/tickets/detail',
                classes: {
                    wrapper: 'hidden-nav-item',
                },
            },
            {
                id: 'tickets.edit',
                title: 'Edit Ticket',
                type: 'basic',
                link: '/tickets/edit',
                classes: {
                    wrapper: 'hidden-nav-item',
                },
            },
        ],
    },
    {
        id: 'access_requests',
        title: 'NAVIGATION.ACCESS_REQUEST',
        translate: 'NAVIGATION.ACCESS_REQUEST',
        type: 'aside',
        icon: 'heroicons_outline:lock-closed',
        link: '/access-requests',
        exactMatch: false,
        badge: {
            title: '8',
            classes: 'bg-red-500 text-white',
        },
        children: [
            {
                id: 'access_requests.dashboard',
                title: 'NAVIGATION.DASHBOARD',
                translate: 'NAVIGATION.DASHBOARD',
                type: 'basic',
                icon: 'heroicons_outline:chart-pie',
                link: '/access-requests/dashboard',
            },
            {
                id: 'access_requests.list',
                title: 'NAVIGATION.ACCESS_REQUESTS',
                translate: 'NAVIGATION.ACCESS_REQUESTS',
                type: 'basic',
                icon: 'heroicons_outline:lock-closed',
                link: '/access-requests/data',
                exactMatch: false,
            },
            {
                id: 'access_requests.create',
                title: 'NAVIGATION.CREATE_ACCESS_REQUEST',
                translate: 'NAVIGATION.CREATE_ACCESS_REQUEST',
                type: 'basic',
                icon: 'heroicons_outline:plus-circle',
                link: '/access-requests/create',
            },
            {
                id: 'access_requests.detail',
                title: 'Access Request Detail',
                type: 'basic',
                link: '/access-requests/detail',
                classes: {
                    wrapper: 'hidden-nav-item',
                },
            },
            {
                id: 'access_requests.edit',
                title: 'Edit Access Request',
                type: 'basic',
                link: '/access-requests/edit',
                classes: {
                    wrapper: 'hidden-nav-item',
                },
            },
        ],
    },
    {
        id: 'change_requests',
        title: 'NAVIGATION.CHANGE_REQUEST',
        translate: 'NAVIGATION.CHANGE_REQUEST',
        type: 'aside',
        icon: 'heroicons_outline:arrow-path',
        link: '/change-requests',
        exactMatch: false,
        badge: {
            title: '5',
            classes: 'bg-red-500 text-white',
        },
        children: [
            {
                id: 'change_requests.dashboard',
                title: 'NAVIGATION.DASHBOARD',
                translate: 'NAVIGATION.DASHBOARD',
                type: 'basic',
                icon: 'heroicons_outline:chart-pie',
                link: '/change-requests/dashboard',
            },
            {
                id: 'change_requests.list',
                title: 'NAVIGATION.CHANGE_REQUESTS',
                translate: 'NAVIGATION.CHANGE_REQUESTS',
                type: 'basic',
                icon: 'heroicons_outline:arrow-path',
                link: '/change-requests/data',
                exactMatch: false,
            },
            {
                id: 'change_requests.create',
                title: 'NAVIGATION.CREATE_CHANGE_REQUEST',
                translate: 'NAVIGATION.CREATE_CHANGE_REQUEST',
                type: 'basic',
                icon: 'heroicons_outline:plus-circle',
                link: '/change-requests/create',
            },
        ],
    },
    {
        id: 'job_requests',
        title: 'NAVIGATION.JOB_REQUEST',
        translate: 'NAVIGATION.JOB_REQUEST',
        type: 'aside',
        icon: 'heroicons_outline:briefcase',
        link: '/job-requests',
        exactMatch: false,
        badge: {
            title: '3',
            classes: 'bg-red-500 text-white',
        },
        children: [
            {
                id: 'job_requests.dashboard',
                title: 'NAVIGATION.DASHBOARD',
                translate: 'NAVIGATION.DASHBOARD',
                type: 'basic',
                icon: 'heroicons_outline:chart-pie',
                link: '/job-requests/dashboard',
            },
            {
                id: 'job_requests.list',
                title: 'NAVIGATION.JOB_REQUESTS',
                translate: 'NAVIGATION.JOB_REQUESTS',
                type: 'basic',
                icon: 'heroicons_outline:briefcase',
                link: '/job-requests/data',
                exactMatch: false,
            },
            {
                id: 'job_requests.create',
                title: 'NAVIGATION.CREATE_JOB_REQUEST',
                translate: 'NAVIGATION.CREATE_JOB_REQUEST',
                type: 'basic',
                icon: 'heroicons_outline:plus-circle',
                link: '/job-requests/create',
            },
        ],
    },
    {
        id: 'master_data',
        title: 'NAVIGATION.MASTER_DATA',
        translate: 'NAVIGATION.MASTER_DATA',
        type: 'aside',
        icon: 'heroicons_outline:circle-stack',
        link: '/master-data',
        exactMatch: false,
        children: [
            {
                id: 'master_data.user',
                title: 'NAVIGATION.USER',
                translate: 'NAVIGATION.USER',
                type: 'basic',
                icon: 'heroicons_outline:users',
                link: '/master-data/users',
            },
            {
                id: 'master_data.department',
                title: 'NAVIGATION.DEPARTMENT',
                translate: 'NAVIGATION.DEPARTMENT',
                type: 'basic',
                icon: 'heroicons_outline:building-office',
                link: '/master-data/departments',
            },
            {
                id: 'master_data.team',
                title: 'NAVIGATION.TEAM',
                translate: 'NAVIGATION.TEAM',
                type: 'basic',
                icon: 'heroicons_outline:user-group',
                link: '/master-data/teams',
            },
            {
                id: 'master_data.ticket_group',
                title: 'Ticket',
                type: 'group',
            },
            {
                id: 'master_data.ticket_source',
                title: 'NAVIGATION.TICKET_SOURCE',
                translate: 'NAVIGATION.TICKET_SOURCE',
                type: 'basic',
                icon: 'heroicons_outline:inbox-stack',
                link: '/master-data/ticket-sources',
            },
            {
                id: 'master_data.help_topic',
                title: 'NAVIGATION.HELP_TOPIC',
                translate: 'NAVIGATION.HELP_TOPIC',
                type: 'basic',
                icon: 'heroicons_outline:question-mark-circle',
                link: '/master-data/help-topics',
            },
            {
                id: 'master_data.access_request_group',
                title: 'Access Request',
                type: 'group',
            },
            {
                id: 'master_data.request_type',
                title: 'NAVIGATION.REQUEST_TYPE',
                translate: 'NAVIGATION.REQUEST_TYPE',
                type: 'basic',
                icon: 'heroicons_outline:clipboard-document-list',
                link: '/master-data/request-types',
            },
            {
                id: 'master_data.access_level',
                title: 'NAVIGATION.ACCESS_LEVEL',
                translate: 'NAVIGATION.ACCESS_LEVEL',
                type: 'basic',
                icon: 'heroicons_outline:shield-check',
                link: '/master-data/access-levels',
            },
        ],
    },
    {
        id: 'settings',
        title: 'NAVIGATION.SETTINGS',
        translate: 'NAVIGATION.SETTINGS',
        type: 'aside',
        icon: 'heroicons_outline:cog-6-tooth',
        link: '/settings',
        exactMatch: false,
        children: [
            {
                id: 'settings.application',
                title: 'NAVIGATION.APPLICATION_SETTING',
                translate: 'NAVIGATION.APPLICATION_SETTING',
                type: 'basic',
                icon: 'heroicons_outline:window',
                link: '/settings/application',
            },
            {
                id: 'settings.smtp',
                title: 'NAVIGATION.SMTP_SETTING',
                translate: 'NAVIGATION.SMTP_SETTING',
                type: 'basic',
                icon: 'heroicons_outline:envelope',
                link: '/settings/smtp',
            },
            {
                id: 'settings.whatsapp',
                title: 'NAVIGATION.WHATSAPP_SETTING',
                translate: 'NAVIGATION.WHATSAPP_SETTING',
                type: 'basic',
                icon: 'heroicons_outline:chat-bubble-left-right',
                link: '/settings/whatsapp',
            },
        ],
    },
];

export const compactNavigation: FuseNavigationItem[] = defaultNavigation;
export const futuristicNavigation: FuseNavigationItem[] = defaultNavigation;
export const horizontalNavigation: FuseNavigationItem[] = defaultNavigation;
