- hosts: helpdesk-fe
  vars:
    image: ioez1984/helpdeskfe

  tasks:
    - name: install python-docker centos
      yum:
        name:
          - python
          - python-docker
        state: present

    - name: pull image docker
      docker_image:
        name: "{{ image }}"
        source: pull
        force_source: yes
        state: present

    - name: create containers
      docker_container:
        name: helpdeskfe-byjenkins
        image: "{{ image }}"
        state: started
        restart_policy: always
        published_ports:
        - 80:80
        recreate: yes

    - name: Remove dangling docker images
      docker_prune:
        images: yes
        images_filters:
          dangling: true

      ignore_errors: yes
      become: true
