- hosts: helpdesk-be
  vars:
    image: ioez1984/helpdeskbe:latest
    remote_app_path: /opt/helpdesk-backend
    storage_mount_path: "/opt/helpdesk-backend/storage_public"

  tasks:
    - name: Ensure application directory exists
      file:
        path: "{{ remote_app_path }}"
        state: directory
        mode: '0755'

    - name: Ensure persistent storage directory exists on VM
      file:
        path: "{{ storage_mount_path }}"
        state: directory
        mode: '0777'

    - name: Deploy .env file
      copy:
        src: "{{ playbook_dir }}/.env"
        dest: "{{ remote_app_path }}/.env"
        mode: '0600'

    - name: pull latest backend image
      docker_image:
        name: "{{ image }}"
        source: pull
        force_source: yes
        state: present

    - name: run laravel container
      docker_container:
        name: helpdesk-byjenkins
        image: "{{ image }}"
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
        volumes:
          - "{{ remote_app_path }}/.env:/var/www/html/.env"
          - "{{ storage_mount_path }}:/var/www/html/storage/app/public"
        recreate: yes

    - name: Fix ownership inside container
      command: docker exec -u root helpdesk-byjenkins chown -R www-data:www-data storage bootstrap/cache

    - name: Generate Laravel storage link
      command: docker exec helpdesk-byjenkins php artisan storage:link
      register: link_cmd
      failed_when: 
        - link_cmd.rc != 0 
        - "'already exists' not in link_cmd.stderr"
      ignore_errors: yes

    - name: Clear Laravel Cache
      command: docker exec helpdesk-byjenkins php artisan optimize:clear

    - name: cleanup dangling images
      shell: |
        oldimage=$(docker images -f "dangling=true" -q)
        if [ -n "$oldimage" ]; then
          docker rmi $oldimage -f
        fi
      ignore_errors: yes
